### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/typesafe/scalalogging/Logger : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by RayTsui** [lightbend/config#505]
When I execute the spark-shell in cluster and I input 
val graphframes = GraphFrame.fromEdges(edges)
it gives me as follows:
java.lang.UnsupportedClassVersionError: com/typesafe/scalalogging/Logger : Unsupported major.minor version 52.0
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  ... 50 elided

If someone met it before and solved it, please give me some hints on it, thanks a lot.

**Comment by WellingR** [comment]
I think you are running on java 6, however form version 1.3.0 java 8 is required
