### ISSUE TITLE
Exception thrown when setting custom ConfigIncluder

### ISSUE THREAD

**Issue by costimuraru** [lightbend/config#535]
I want to include a URL, but with some special logic (eg. authentication) and some placeholders.

```
role = mywebapp
role = ${?APP_ROLE}

include url("http://server/${role}")
```

Following the discussions on other threads I tried defining a custom ConfigIncluder.

```java
public class CustomConfigIncluder implements ConfigIncluder, ConfigIncluderURL {
    private ConfigIncluder fallback;

    @Override
    public ConfigIncluder withFallback(ConfigIncluder fallback) {
        this.fallback = fallback;
        return this;
    }

    @Override
    public ConfigObject include(ConfigIncludeContext context, String what) {
        return fallback.include(context, what);
    }

    @Override
    public ConfigObject includeURL(ConfigIncludeContext context, URL what) {
        return ConfigFactory.empty().root(); // TODO: my custom logic here: authentication + replace placeholders
    }
}
```

Then this code to parse the above `reference.conf` file:
```java
Config config = ConfigFactory.load("reference.conf",
                ConfigParseOptions.defaults().setIncluder(new CustomConfigIncluder()).setAllowMissing(false),
                ConfigResolveOptions.defaults())
                .resolve();
```

Expected behaviour:
Use the `CustomConfigIncluder` to parse the URL. This includer is dummy, it just returns ConfigFactory.empty().root() - no harm, no foul.

Actual behavior:
When doing the `ConfigFactory.load(...)` call, the typesafe library is actually parsing the `reference.conf` file twice. First, using `CustomConfigIncluder`, which works as expected. Then it goes through another round of parsing the HARD-CODED reference.conf file, this time with the SimpleIncluder (see here https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigImpl.java#L368)
This second parsing attempt (which uses the typesafe-provided SimpleIncluder) fails, because as far as it is concerned, `http://server/${role}` is a BAD url.

```
Exception in thread "main" com.typesafe.config.ConfigException$BugOrBroken: Cannot load config from URL: http://server/${role}
	at com.typesafe.config.impl.Parseable$ParseableURL.reader(Parseable.java:569)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:231)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseURL(ConfigFactory.java:655)
	at com.typesafe.config.impl.SimpleIncluder.includeURLWithoutFallback(SimpleIncluder.java:87)
	at com.typesafe.config.impl.SimpleIncluder.includeURL(SimpleIncluder.java:75)
	at com.typesafe.config.impl.ConfigParser$ParseContext.parseInclude(ConfigParser.java:172)
	at com.typesafe.config.impl.ConfigParser$ParseContext.parseObject(ConfigParser.java:237)
	at com.typesafe.config.impl.ConfigParser$ParseContext.parseValue(ConfigParser.java:103)
	at com.typesafe.config.impl.ConfigParser$ParseContext.parse(ConfigParser.java:415)
	at com.typesafe.config.impl.ConfigParser.parse(ConfigParser.java:25)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:261)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:307)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:747)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.impl.ConfigImpl$1.call(ConfigImpl.java:373)
	at com.typesafe.config.impl.ConfigImpl$1.call(ConfigImpl.java:367)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
	at com.typesafe.config.impl.ConfigImpl.defaultReference(ConfigImpl.java:367)
	at com.typesafe.config.ConfigFactory.defaultReference(ConfigFactory.java:367)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:213)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:115)
	at com.mypackage.Main.main(Main.java:13)
```

What is up with this hard-coded parsing of the `reference.conf`, which simply overrides the custom config includer that was defined programatically?
https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigImpl.java#L368
If I change the file name from reference.conf to my_reference.conf, the error seems to go away, but this looks a bit unnatural. Is there any way to instruct the parser to ALWAYS use the custom config includer?

Any help is appreciated.

Thank you.

**Comment by havocp** [comment]
I think the confusion is around exactly the spec for ConfigFactory.load.

`ConfigFactory.load()` with no parameters loads defaultReference, then application.conf, then defaultOverrides.

`ConfigFactory.load("somename")` replaces the application.conf part with somename.conf

`ConfigFactory.load("application")` I think is the same as having no parameters.

The passed-in filename and options don't change defaultReference or defaultOverrides, only the middle of the sandwich.

If you want lower-level control there are a bunch of methods that start with `parse`; `load` variants give you the default behavior, `parse` parses individual items and you can stack them yourself with `withFallback`.

I think the javadoc is fairly thorough but there are a lot of methods to track down to get the whole picture I suppose.

**Comment by havocp** [comment]
Closing but feel free to open if there's a bug to be fixed. Also consider the gitter room or stackoverflow for support-type questions.

**Comment by sojanmathew** [comment]
```
package com.intuit.network.graph.pipeline;

import com.typesafe.config.*;
import com.typesafe.config.impl.Parseable;

public class CustomConfigIncluder implements ConfigIncluder, ConfigIncluderClasspath {
    private ConfigIncluder fallback =  Parseable.newString("", ConfigParseOptions.defaults()).options().getIncluder();

    @Override
    public ConfigIncluder withFallback(ConfigIncluder fallback) {
        this.fallback = fallback;
        return this;
    }

    @Override
    public ConfigObject include(ConfigIncludeContext context, String what) {
        return fallback.include(context, what);
    }

    @Override
    public ConfigObject includeResources(ConfigIncludeContext context, java.lang.String what){
        int idx = -1;
        if ((idx= what.indexOf("${")) > 0){
            int end = what.indexOf('}',idx);
            String envVar = what.substring(idx+2,end);
            System.out.println(envVar+" = "+System.getProperty(envVar) );
            return fallback.include(context, what.replace("${"+envVar+"}",System.getProperty(envVar)));
        }
        else {
            return ((ConfigIncluderClasspath) fallback).includeResources(context, what);
        }
    }
}
```

```
System.setProperty("env","qa"); // take env as named argument from command line along with value
var parseOptions : ConfigParseOptions = ConfigParseOptions.defaults.setIncluder(new CustomConfigIncluder());
    var conf :Config  = ConfigFactory.parseString(pipelineConfText,parseOptions);
    val typesafeConf = conf.resolve(ConfigResolveOptions.defaults())
```
sample conf file : (myworkflow.conf)
```
include required(classpath("config/WorkflowBase_${env}.conf"))
section1 {
     name = "myworkflow"
}
```
