### ISSUE TITLE
ConfigException$Missing thrown when config is in resource folder

### ISSUE THREAD

**Issue by NiflheimDev** [lightbend/config#544]
Exception gets thrown if conf file is in resource folder (grabbed with classloader) but if I move the conf to root directory and change the path, everything works fine.

**Comment by raboof** [comment]
How are you loading the config? Can you share the invocation and the complete stack trace?

`ConfigFactory.load()` certainly successfully loads the configuration from the classpath for many projects...

**Comment by NiflheimDev** [comment]
I first used 
```
ConfigFactory.parseFile(new File(Settings.class.getResource("/automata/config.conf").getFile()));
```
to grab it from my resources folder but would receive this error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at xyz.rethink.database.Rethink.<init>(Rethink.java:25)
	at xyz.automata.Automata.main(Automata.java:20)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'System'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at xyz.niflheim.utils.Settings.<clinit>(Settings.java:13)
	... 2 more
```

If I were to change the path to the project root directory and update pathing, it would work just fine.
I have also tried ConfigFactory.load(); but for some reason that would throw the same error whether or not the config.conf was in the project root or resources folder.

**Comment by raboof** [comment]
Ah, `ConfigFactory.load()` expects the configuration to be in one of the locations mentioned at https://github.com/lightbend/config#standard-behavior, so indeed it will not pick up a `config.conf` file.

I would recommend using `ConfigFactory.load` and adopt the conventions detailed there.
