### ISSUE TITLE
Cannot guess syntax from reader

### ISSUE THREAD

**Issue by ntviet18** [lightbend/config#572]
Hello Everyone,

It seems like currently config parser can only guess the syntax from the file name, e.g.

Given `application.properties`
```properties
app=hello^^
```

`ConfigFactory.parse("application.properties")` will work perfectly fine, resolving `app` to the string `"hello^^"`

However, `ConfigFactory.parseReader(new InputStreamReader(new FileInputStream("application.properties")))` will fail with 

```
Reader: 1: Expecting end of input or a comma, got '^' (Reserved character '^' is not allowed outside quotes) (if you intended '^' (Reserved character '^' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
com.typesafe.config.ConfigException$Parse: Reader: 1: Expecting end of input or a comma, got '^' (Reserved character '^' is not allowed outside quotes) (if you intended '^' (Reserved character '^' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:535)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:623)
	at com.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:637)
```

Can we make it fallback to reading properties internally?

**Comment by havocp** [comment]
there’s an overload of parseReader that takes a ConfigParseOptions allowing you to specify the syntax https://lightbend.github.io/config/latest/api/com/typesafe/config/ConfigParseOptions.html

**Comment by ntviet18** [comment]
Hi @havocp , thank you for your quick answer.
I'm aware of the overloaded method and using it for the moment.
Do you have any plan to implement or accept such pull request?

**Comment by havocp** [comment]
I don’t love the idea of trying one syntax and then another; to me it creates nondeterministic / poorly-defined behavior especially when there are files valid in both syntaxes that would be interpreted differently depending on which is chosen

**Comment by havocp** [comment]
Somehing like `ConfigParseOptions.setSyntaxFromFilename` might be useful? to factor out the extension handling

**Comment by ntviet18** [comment]
I agree. There are probably already some people relying on the current default behavior as well.
I think `setSyntaxFromFilename` is a good solution. At least people don't have to choose the syntax manually every time. We can also make it synchronized with `parseFile` behavior.
I can help you with this.

**Comment by havocp** [comment]
Cool! It looks a bit awkward to refactor existing code (see https://github.com/lightbend/config/blob/4edef986f417355095ce277ccdab9d4b5a2a884b/config/src/main/java/com/typesafe/config/impl/Parseable.java#L60-L68 )  but I think the only thing to really be sure not to cut-and-paste is this syntaxFromExtension method: https://github.com/lightbend/config/blob/4edef986f417355095ce277ccdab9d4b5a2a884b/config/src/main/java/com/typesafe/config/impl/Parseable.java#L329-L338

Maybe could stick syntaxFromExtension in some common location (static method on ConfigImplUtil maybe)? and avoid changing a lot of code ... see what you think makes sense

**Comment by ntviet18** [comment]
@havocp , thank you for your advice. 
Could you please review my pull request?
