### ISSUE TITLE
Mixin substitutions affect resolution inside of the object being mixed into, causing errors

### ISSUE THREAD

**Issue by netvl** [lightbend/config#586]
Consider this config object:
```
mixin {
  hello = world
}
a = ${mixin} {
  ext {
    x = 12
  }
  y = ${a.ext.x}
}
```
Parsing it like this:
```scala
ConfigFactory.parseString(config).resolve()
```
results in an exception:
```
Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: String: 9: Could not resolve substitution to a value: ${a.ext.x} was part of a cycle of substitutions involving ${a.ext.x}, ${a.ext.x}
	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:104)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
	at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:78)
	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:68)
	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:63)
	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:41)
	at sandbox.ConfigTest$.delayedEndpoint$com$apple$amp$ae$sandbox$ConfigTest$1(ConfigTest.scala:18)
	at sandbox.ConfigTest$delayedInit$body.apply(ConfigTest.scala:5)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at sandbox.ConfigTest$.main(ConfigTest.scala:5)
	at sandbox.ConfigTest.main(ConfigTest.scala)
Caused by: com.typesafe.config.impl.AbstractConfigValue$NotPossibleToResolve: was not possible to resolve
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:176)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:365)
	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
	at com.typesafe.config.impl.ResolveSource.findInObject(ResolveSource.java:47)
	at com.typesafe.config.impl.ResolveSource.lookupSubst(ResolveSource.java:97)
	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:74)
	... 31 more
```
The following changes all fix the problem:
1. Removing the `${mixin}` substitution
2. Replacing the `${a.ext.x}` with something like `${outer.x}` (with the `outer` object defined)
3. Replacing the `${mixin}` substitution with literal object rather than reference

So this seems to be contained to a case when two objects are being merged, and there is a reference to the final object in one of them.

This seems like something which should work fine, because there is no unclear semantics here, or at least I don't see it: the `${mixin}` object is completely unrelated to the offending substitution. I suspect that this is a bug, but if I'm wrong I would really like to know why :)

**Comment by havocp** [comment]
It probably is a bug but the code to handle (apparently only most) cases like this is complicated as hell. There's a detailed explanation of how it should work in https://github.com/lightbend/config/blob/master/HOCON.md#self-referential-substitutions and there are quite a few unit tests. The way I'd tackle this is to add a unit test like this - be sure it still happens on latest master! I totally redid how this works at one point - and then we'd have to try to fix it without breaking any of the existing unit tests.
