### ISSUE TITLE
include file not working for relative path (for non-default conf)

### ISSUE THREAD

**Issue by purijatin** [lightbend/config#594]
Here is my folder structure:

```
a/b/c/app.conf
a/b/c/1.conf
a/b/c/2.conf
```

The contents of `app.conf` is:

```
app {
  include required(file("1.conf"))
  include required(file("2.conf"))
}
```

When I load the file `a/b/c/app.conf` via:
```scala
ConfigFactory.parseFile("a/b/c/app.conf")
```

This results in the below exception:
```
Caused by: com.typesafe.config.ConfigException$IO: 1.conf: java.io.FileNotFoundException: 1.conf (No such file or directory)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
```

It works if I mention the path as `required(file(a/b/c/1.conf))` inside `app.conf` instead. What can I do so that the path is taken relatively.

**Comment by havocp** [comment]
I think it is this bug: 
https://github.com/lightbend/config/issues/202

**Comment by purijatin** [comment]
Ok. 
Thanks for the quick response.
