### ISSUE TITLE
UTFDataFormatException in SerializedConfigValue.scala:314

### ISSUE THREAD

**Issue by joe-mojo** [lightbend/config#627]
The exact message is : 
```
java.io.UTFDataFormatException: encoded string too long: 93067 bytes
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
        at com.typesafe.config.impl.SerializedConfigValue.writeValueData(SerializedConfigValue.java:314)
```
Java DataOutputStream's writeUTF method states that it cannot write more than 65535 bytes, but Typesafe/Lighbend config don't report nor try to workaround this limitation. 
Thus, when serializing a Config object, if any String is more than 65535 bytes, it is not serializable.

Perhaps you could write UTF String by calling multiple times the writeUTF method ?
Example :
1) write an UTF string header
2) write the number of write/readUTF than will be necesary
3) write the string by spliting it into frames of max 65535 bytes, calling as much writeUTF as necessary.

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/geotools/geotools. Perhaps we can refer to https://github.com/geotools/geotools/pull/2265 to find more context about the bug (e.g. their steps to reproduce?). 
Or maybe this can help us find the faulty lines and we can also refer to the https://github.com/geotools/geotools/pull/2265/commits/7b52e15943846f72f0d85cc9121d330daf8c6c6e# for the bug?

I wrote a fixed version by myself and propose a PR: https://github.com/lightbend/config/pull/703. Maybe you can also check that. Let me know if you have further questions. Thanks!
