### ISSUE TITLE
StackOverflowError when OS has a lot of environment variables

### ISSUE THREAD

**Issue by extbe** [lightbend/config#700]
Hi!

**Versions**
config v1.4.0
Java 11.0.2

**Description**
I try to run my application on OS with about 700 environment variables. I have a config file with substitution `test = ${ENV_VARIABLE}` and next code to create `Config`:

```java
Config conf = ConfigFactory.systemProperties()
                .withFallback(ConfigFactory.parseResources("test.conf"))
                .withFallback(ConfigFactory.systemEnvironment())
                .resolve();
```

Also I limit thread stack size to 210k using `-Xss210k`, so the application fails with an error (I skipped the rest of stack trace because it is about 900 lines long) 
```
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1041)
	at java.base/java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1041)
	at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1042)
	at java.base/java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1041)
	at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1042)
	at java.base/java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1041)
	at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1042)
	at java.base/java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1041)
```

I noticed that if I remove the substitution or `.withFallback(ConfigFactory.systemEnvironment())` then the application starts.

I debugged and found that in the [ResolveContext](https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ResolveContext.java) each call to [pushTrace](https://github.com/lightbend/config/blob/e0984d41b040d64b650c7014108a7db9dd451457/config/src/main/java/com/typesafe/config/impl/ResolveContext.java#L115) or [popTrace](https://github.com/lightbend/config/blob/e0984d41b040d64b650c7014108a7db9dd451457/config/src/main/java/com/typesafe/config/impl/ResolveContext.java#L123) wraps `cycleMarkers` into another `UnmodifiableSet` (because the constructor does it), even though it's already an `UnmodifiableSet`.

**Comment by extbe** [comment]
@havocp, is there anything else that has to be done before accepting the pull request? I've checked a modified version from the pull request and it seems that the issue has been solved.

**Comment by havocp** [comment]
Nothing else afaik, thanks for testing. Just not a lot of active maintenance happening here unfortunately so things are slow.
