### ISSUE TITLE
Failed to serialize a config with long string value

### ISSUE THREAD

**Issue by sevdokimov** [lightbend/config#727]
I get the following exception when trying to serialize a config with a long string value (longer than 65535 bytes)

```
java.io.UTFDataFormatException: encoded string too long: 90000 bytes
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
	at com.typesafe.config.impl.SerializedConfigValue.writeValueData(SerializedConfigValue.java:316)
	at com.typesafe.config.impl.SerializedConfigValue.writeValue(SerializedConfigValue.java:390)
	at com.typesafe.config.impl.SerializedConfigValue.writeValueData(SerializedConfigValue.java:330)
	at com.typesafe.config.impl.SerializedConfigValue.writeValue(SerializedConfigValue.java:390)
	at com.typesafe.config.impl.SerializedConfigValue.writeExternal(SerializedConfigValue.java:456)
	at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1459)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1430)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.typesafe.config.impl.BigConfigSerializationTest.testBigConfigSerialization(BigConfigSerializationTest.java:30)
```

One possible fix: https://github.com/sevdokimov/config/pull/1/commits/16b9ac86773542a2548e7b20b1f8ea95ca741974

**Comment by HalorScala** [comment]
Duplicates https://github.com/lightbend/config/issues/627?
